!WRF:MEDIATION_LAYER:ADT_BARRIER
!

! Matt Onderlinde Sep, 2013
! Add nudge base profile variables to solve_interface() subroutine
SUBROUTINE solve_interface ( grid,                 &
                             uold_base,            &
                             vold_base,            &
                             told_base,            &
                             qold_base,            &
                             unew_base,            &
                             vnew_base,            &
                             tnew_base,            &
                             qnew_base,            &
                             nudge_indicator,      &
                             d01_gfdda_interval_m  )

   USE module_domain
   USE module_timing
   USE module_driver_constants
   USE module_configure
   USE module_wrf_error
#if( EM_CORE == 1 )
   USE module_trajectory, only : trajectory_driver
#endif

   IMPLICIT NONE

   INTERFACE
#if (EM_CORE == 1 && DA_CORE != 1)
# include  "solve_em.int"
#endif
   END INTERFACE

   TYPE(domain) , INTENT(INOUT)  :: grid
   TYPE (grid_config_rec_type)   :: config_flags

   INTEGER     :: idum1, idum2
   CHARACTER(len=256) :: dbg_msg

   ! Matt Onderlinde Sep, 2013
   ! Introduce variables for u_base, v_base, t_base, qv_base based on the
   ! nudging input
   REAL, DIMENSION(:,:), ALLOCATABLE, INTENT(IN) :: uold_base
   REAL, DIMENSION(:,:), ALLOCATABLE, INTENT(IN) :: vold_base
   REAL, DIMENSION(:,:), ALLOCATABLE, INTENT(IN) :: told_base
   REAL, DIMENSION(:,:), ALLOCATABLE, INTENT(IN) :: qold_base
   REAL, DIMENSION(:,:), ALLOCATABLE, INTENT(IN) :: unew_base
   REAL, DIMENSION(:,:), ALLOCATABLE, INTENT(IN) :: vnew_base
   REAL, DIMENSION(:,:), ALLOCATABLE, INTENT(IN) :: tnew_base
   REAL, DIMENSION(:,:), ALLOCATABLE, INTENT(IN) :: qnew_base
   INTEGER, INTENT(IN) :: nudge_indicator, d01_gfdda_interval_m

   CALL model_to_grid_config_rec ( grid%id , model_config_rec , config_flags )
   CALL set_scalar_indices_from_config ( grid%id , idum1 , idum2 )

#if (EM_CORE == 1 && DA_CORE != 1)
   
#if ( WRFPLUS == 1 )
   IF      ( config_flags%dyn_opt == dyn_em_tl ) THEN
      CALL solve_em_tl  ( grid , config_flags  &
!
# include "actual_new_args.inc"
!
               )
   ELSE IF ( config_flags%dyn_opt == dyn_em_ad ) THEN
      CALL solve_em_ad  ( grid , config_flags  &
!
# include "actual_new_args.inc"
!
               )
   ELSE
#endif

   ! Matt Onderlinde Sep, 2013
   ! Add nudge base profile variables to solve_em() call
   CALL solve_em  ( grid , config_flags ,              &
                    uold_base,                         &
                    vold_base,                         &
                    told_base,                         &
                    qold_base,                         &
                    unew_base,                         &
                    vnew_base,                         &
                    tnew_base,                         &
                    qnew_base,                         &
                    nudge_indicator,                   &
                    d01_gfdda_interval_m               &
!
# include "actual_new_args.inc"
!
               )
#if ( WRFPLUS == 1 )
   END IF
#endif

# if ( WRF_CHEM == 1 )
   IF ( config_flags%chem_opt > 0 .or. config_flags%tracer_opt > 0 ) THEN

     CALL chem_driver  ( grid , config_flags  &
!
# include "actual_new_args.inc"
!
               )
   ENDIF
# endif
#endif

# if ( EM_CORE == 1 && WRFPLUS != 1 )
   if( grid%traj_opt /= no_trajectory ) then
     write(dbg_msg,'(''solve_xface('',i2.2,''): Before call to trajectory_driver'')') grid%id
     call wrf_debug( 200,trim(dbg_msg) )
     call trajectory_driver( grid )
     write(dbg_msg,'(''solve_xface('',i2.2,''): After  call to trajectory_driver'')') grid%id
     call wrf_debug( 200,trim(dbg_msg) )
   endif
# endif

END SUBROUTINE solve_interface

